name: Build and Deploy

on:
  push:
    branches:
      - main  # main ブランチにプッシュされたとき

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 他のステップを追加する場合

      - name: Build Jekyll site
        run: bundle exec jekyll build --config docs/_config.yml
        env:
          JEKYLL_ENV: production
